services:
  pgsql:
    image: bitnami/postgresql
    container_name: pgsql
    environment:
      - POSTGRESQL_USERNAME=dbpg
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pgGympass
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - db_network

  api:
    build: .
    container_name: api
    networks:
      - db_network
      - api_network
    ports:
      - 3333:3333
    depends_on:
      - pgsql

networks:
  db_network:
  api_network:

volumes:
  pg_data:
