version: '3'

services:
  pgsql:
    image: bitnami/postgresql
    container_name: pgsql
    ports:
      - 5432:5432
    networks:
      - db_network
    environment:
      - POSTGRESQL_USERNAME=dbpg
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pgGympass
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  api:
    build: .
    container_name: api
    networks:
      - api_network
      - db_network
    depends_on:
      - pgsql
networks:
  api_network:
    driver: bridge
  db_network:
    driver: bridge
volumes:
  pg_data:
